### ISSUE TITLE
APP: crash on connecting to Brick

### ISSUE THREAD

**Issue by MarcelMann** [Echtzeitsysteme/mindroid#131]

**Comment by TorbenU** [comment]
--------- beginning of crash
07-14 18:15:26.627 22799-23790/? E/AndroidRuntime: FATAL EXCEPTION: Thread-676
    Process: org.mindroid.android.app, PID: 22799
    java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.next(ArrayList.java:831)
        at org.mindroid.impl.sensor.EV3SensorEndpoint.handleSensorEvent(EV3SensorEndpoint.java:128)
        at org.mindroid.impl.sensor.EV3SensorEndpoint$1.run(EV3SensorEndpoint.java:92)

**Comment by TorbenU** [comment]
Concurrent array list for listeners in EV3SensorEndpoint necessary

**Comment by TorbenU** [comment]
Seems to be solved.
