### ISSUE TITLE
App-Settings: Invalid IP can lead to an exception

### ISSUE THREAD

**Issue by TorbenU** [Echtzeitsysteme/mindroid#25]
- Enter some ip like "001" and press the "Save"-button

04-18 17:02:46.846: E/AndroidRuntime(4563): FATAL EXCEPTION: main
04-18 17:02:46.846: E/AndroidRuntime(4563): Process: org.mindroid.android.app, PID: 4563
04-18 17:02:46.846: E/AndroidRuntime(4563): java.lang.RuntimeException: Unable to start activity ComponentInfo{org.mindroid.android.app/org.mindroid.android.app.acitivites.MainActivity}: android.os.NetworkOnMainThreadException
04-18 17:02:46.846: E/AndroidRuntime(4563): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2195)
04-18 17:02:46.846: E/AndroidRuntime(4563): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
04-18 17:02:46.846: E/AndroidRuntime(4563): 	at android.app.ActivityThread.access$800(ActivityThread.java:135)
04-18 17:02:46.846: E/AndroidRuntime(4563): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
04-18 17:02:46.846: E/AndroidRuntime(4563): 	at android.os.Handler.dispatchMessage(Handler.java:102)
04-18 17:02:46.846: E/AndroidRuntime(4563): 	at android.os.Looper.loop(Looper.java:136)
04-18 17:02:46.846: E/AndroidRuntime(4563): 	at android.app.ActivityThread.main(ActivityThread.java:5017)
04-18 17:02:46.846: E/AndroidRuntime(4563): 	at java.lang.reflect.Method.invokeNative(Native Method)
04-18 17:02:46.846: E/AndroidRuntime(4563): 	at java.lang.reflect.Method.invoke(Method.java:515)
04-18 17:02:46.846: E/AndroidRuntime(4563): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
04-18 17:02:46.846: E/AndroidRuntime(4563): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
04-18 17:02:46.846: E/AndroidRuntime(4563): 	at dalvik.system.NativeStart.main(Native Method)
04-18 17:02:46.846: E/AndroidRuntime(4563): Caused by: android.os.NetworkOnMainThreadException
04-18 17:02:46.846: E/AndroidRuntime(4563): 	at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1145)
04-18 17:02:46.846: E/AndroidRuntime(4563): 	at java.net.InetAddress.lookupHostByName(InetAddress.java:385)
04-18 17:02:46.846: E/AndroidRuntime(4563): 	at java.net.InetAddress.getAllByNameImpl(InetAddress.java:236)
04-18 17:02:46.846: E/AndroidRuntime(4563): 	at java.net.InetAddress.getByName(InetAddress.java:289)
04-18 17:02:46.846: E/AndroidRuntime(4563): 	at org.mindroid.impl.robot.RobotFactory.createRobot(RobotFactory.java:161)
04-18 17:02:46.846: E/AndroidRuntime(4563): 	at org.mindroid.android.app.robodancer.Robot.makeRobot(Robot.java:68)
04-18 17:02:46.846: E/AndroidRuntime(4563): 	at org.mindroid.android.app.acitivites.MainActivity.loadConnectionProperties(MainActivity.java:335)
04-18 17:02:46.846: E/AndroidRuntime(4563): 	at org.mindroid.android.app.acitivites.MainActivity.onCreate(MainActivity.java:120)
04-18 17:02:46.846: E/AndroidRuntime(4563): 	at android.app.Activity.performCreate(Activity.java:5231)
04-18 17:02:46.846: E/AndroidRuntime(4563): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
04-18 17:02:46.846: E/AndroidRuntime(4563): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159)
04-18 17:02:46.846: E/AndroidRuntime(4563): 	... 11 more

**Comment by TorbenU** [comment]
[RuntimeException.txt](https://github.com/Echtzeitsysteme/mindroid/files/930145/RuntimeException.txt)
