### ISSUE TITLE
App: Show error log of EV3

### ISSUE THREAD

**Issue by RolandKluge** [Echtzeitsysteme/mindroid#59]
It would be extremely helpful to "fetch" the error file from the EV3 brick to be able to investigate problems without re-connecting the EV3 brick to the PC.

In my particular case, it appears that I have misconfigured the ColorSensor in the app:
I chose Modus "RGB" and found the following stacktrace in the file "org.mindroid.....err":
```
java.lang.ArrayIndexOutOfBoundsException: 1
        at lejos.hardware.sensor.EV3ColorSensor$ModeProvider.fetchSample(EV3ColorSensor.java:121)
        at lejos.hardware.sensor.BaseSensor.fetchSample(BaseSensor.java:91)
        at mindroid.common.ev3.endpoints.sensors.ev3.AbstractSensor$1.run(AbstractSensor.java:107)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by TorbenU** [comment]
@RolandKluge Fixed the bug responsible for the Exception.
